### ISSUE TITLE
bugs i found with KrIs

### ISSUE THREAD

**Issue by vos6434** [BubbleTrouble14/ARKCraft#10]
Hide armor dosent have textures
flashlight is very glitchy
pistol,longneck rifle,fabricated pistol can zoom in without scope attachment
theres no recipe shows for stuff in mortal and pedstal
spear projectile does not render for other players

**Comment by LewisMcReu** [comment]
Flashlight issues are known, and will probably not be fixed soon.
Hide armor still has to be textured.
Mortar and pestle is still to be reworked
3 and 5 noted

**Comment by LewisMcReu** [comment]
Can't seem to reproduce bug 3. Please provide more info as to how you triggered it.

**Comment by ronickg** [comment]
Bug 3 was fixed by me.

**Comment by LewisMcReu** [comment]
2 improved by me (a lot!)
