### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by KrIsCrEeP** [BubbleTrouble14/ARKCraft#12]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.8-2.0.14.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 4.9.2016 12:14
Description: Exception in world tick

java.lang.NullPointerException: Exception in world tick
    at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:916)
    at net.minecraft.world.World.func_175690_a(World.java:2341)
    at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1192)
    at net.minecraft.client.multiplayer.ChunkProviderClient.func_73156_b(ChunkProviderClient.java:85)
    at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:118)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2112)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:916)
    at net.minecraft.world.World.func_175690_a(World.java:2341)
    at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1192)
    at net.minecraft.client.multiplayer.ChunkProviderClient.func_73156_b(ChunkProviderClient.java:85)

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [EntityPlayerSP['xX_KrIsCrEeP_Xx'/6468, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options:
    Level spawn location: 220,00,64,00,256,00 - World: (220,64,256), Chunk: (at 12,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1410969 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 111 total; [EntityPlayerSP['xX_KrIsCrEeP_Xx'/6468, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityChicken['Dodo'/3074, l='MpServer', x=254,59, y=80,00, z=21,47], EntityXPOrb['Experience Orb'/17411, l='MpServer', x=244,59, y=77,00, z=-128,69], EntityChicken['Dodo'/3075, l='MpServer', x=253,81, y=80,00, z=24,50], EntityXPOrb['Experience Orb'/17412, l='MpServer', x=243,53, y=77,00, z=-127,63], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=221,16, y=79,00, z=52,63], EntityChicken['Dodo'/3090, l='MpServer', x=256,47, y=80,00, z=20,81], EntitySheep['Sheep'/16659, l='MpServer', x=349,38, y=71,09, z=7,50], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=148,81, y=64,00, z=26,69], EntityXPOrb['Experience Orb'/17431, l='MpServer', x=223,25, y=82,00, z=-93,91], EntityZombie['Zombie'/15899, l='MpServer', x=247,50, y=43,00, z=-47,50], EntityZombie['Zombie'/15900, l='MpServer', x=247,50, y=43,00, z=-48,50], EntityZombie['Zombie'/15901, l='MpServer', x=247,50, y=43,00, z=-49,50], EntityItem['item.item.egg'/12574, l='MpServer', x=256,03, y=80,00, z=21,13], EntityZombie['Zombie'/16678, l='MpServer', x=256,50, y=19,00, z=26,06], EntityZombie['Zombie'/17702, l='MpServer', x=256,50, y=29,02, z=-50,50], EntityZombie['Zombie'/16679, l='MpServer', x=257,50, y=18,00, z=15,50], EntityZombie['Zombie'/17703, l='MpServer', x=256,50, y=29,02, z=-49,50], EntitySkeleton['Skeleton'/16940, l='MpServer', x=211,50, y=56,00, z=23,50], EntityCreeper['Creeper'/15660, l='MpServer', x=221,50, y=61,00, z=34,50], EntityCreeper['Creeper'/15661, l='MpServer', x=222,50, y=61,00, z=33,50], EntityZombie['Zombie'/17715, l='MpServer', x=338,50, y=28,02, z=35,50], EntityZombie['Zombie'/17716, l='MpServer', x=340,50, y=28,02, z=38,50], EntityZombie['Zombie'/17717, l='MpServer', x=336,50, y=28,02, z=36,50], EntitySheep['Sheep'/3396, l='MpServer', x=263,47, y=85,00, z=-40,19], EntitySheep['Sheep'/3397, l='MpServer', x=198,72, y=90,00, z=-40,81], EntitySheep['Sheep'/16710, l='MpServer', x=353,38, y=75,00, z=9,19], EntitySheep['Sheep'/16713, l='MpServer', x=355,84, y=75,00, z=25,94], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityBat['Bat'/16474, l='MpServer', x=257,50, y=18,69, z=17,35], EntityBat['Bat'/16475, l='MpServer', x=242,49, y=21,33, z=32,67], EntityItem['item.item.arrow'/13664, l='MpServer', x=223,84, y=80,00, z=13,28], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28], EntityBat['Bat'/17768, l='MpServer', x=238,50, y=28,00, z=-55,50], EntityBat['Bat'/17770, l='MpServer', x=238,40, y=28,06, z=-56,33], EntitySkeleton['Skeleton'/14967, l='MpServer', x=233,50, y=42,00, z=-32,50], EntityBat['Bat'/17281, l='MpServer', x=223,66, y=39,06, z=23,68], EntityItem['item.item.egg'/11396, l='MpServer', x=253,75, y=80,00, z=24,41], EntityCreeper['Creeper'/17314, l='MpServer', x=320,25, y=30,30, z=-49,31], EntitySpider['Spider'/13475, l='MpServer', x=230,50, y=16,00, z=-24,50], EntityBat['Bat'/17572, l='MpServer', x=199,48, y=58,31, z=5,66], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityZombie['Zombie'/15529, l='MpServer', x=222,63, y=81,00, z=17,06], EntitySkeleton['Skeleton'/15530, l='MpServer', x=214,75, y=80,00, z=18,81], EntitySkeleton['Skeleton'/15531, l='MpServer', x=215,50, y=80,00, z=22,50], EntitySkeleton['Skeleton'/16300, l='MpServer', x=266,50, y=40,00, z=-10,50], EntitySkeleton['Skeleton'/16301, l='MpServer', x=268,50, y=40,00, z=-10,50], EntityCreeper['Creeper'/15534, l='MpServer', x=199,50, y=17,00, z=17,50], EntityEnderman['Enderman'/16562, l='MpServer', x=221,50, y=26,00, z=-65,50], EntityZombie['Zombie'/16819, l='MpServer', x=257,38, y=45,00, z=-42,00], EntityZombie['Zombie'/16820, l='MpServer', x=251,63, y=43,00, z=-54,13], EntityZombie['Zombie'/16821, l='MpServer', x=253,34, y=44,00, z=-52,19], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/2999, l='MpServer', x=214,03, y=82,50, z=63,50], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityArmorStand['Armor Stand'/3000, l='MpServer', x=213,50, y=80,00, z=57,50], EntitySkeleton['Skeleton'/16056, l='MpServer', x=200,88, y=41,00, z=51,44], EntityItemFrame['entity.ItemFrame.name'/3001, l='MpServer', x=214,03, y=80,50, z=61,50], EntityPlayerDummy['entity.rfpr.PlayerDummy.name'/186, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityArmorStand['Armor Stand'/3002, l='MpServer', x=213,50, y=80,00, z=53,50], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/3003, l='MpServer', x=214,03, y=80,50, z=63,50], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/3004, l='MpServer', x=214,03, y=80,50, z=62,50], EntityItemFrame['entity.ItemFrame.name'/3005, l='MpServer', x=214,03, y=80,50, z=60,50], EntitySkeleton['Skeleton'/17341, l='MpServer', x=220,50, y=80,00, z=14,50], EntityArmorStand['Armor Stand'/3006, l='MpServer', x=213,50, y=80,00, z=55,50], EntityBat['Bat'/15294, l='MpServer', x=196,53, y=55,45, z=5,46], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28], EntityItemFrame['entity.ItemFrame.name'/3007, l='MpServer', x=214,03, y=80,50, z=59,50], EntityArmorStand['Armor Stand'/3008, l='MpServer', x=213,50, y=80,00, z=51,50], EntityBat['Bat'/17093, l='MpServer', x=213,54, y=48,82, z=7,71], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityXPOrb['Experience Orb'/17355, l='MpServer', x=278,91, y=74,00, z=-106,78], EntityXPOrb['Experience Orb'/17356, l='MpServer', x=280,66, y=74,00, z=-107,25], EntityCreeper['Creeper'/14293, l='MpServer', x=246,50, y=15,00, z=-19,50], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityXPOrb['Experience Orb'/17375, l='MpServer', x=276,38, y=74,00, z=-102,41], EntityXPOrb['Experience Orb'/17376, l='MpServer', x=277,06, y=74,00, z=-102,59], EntityItem['item.item.string'/13537, l='MpServer', x=217,81, y=73,00, z=31,56], EntityXPOrb['Experience Orb'/13540, l='MpServer', x=216,59, y=73,00, z=32,28], EntityZombie['Zombie'/16356, l='MpServer', x=200,50, y=49,00, z=26,50], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityXPOrb['Experience Orb'/13541, l='MpServer', x=215,06, y=73,00, z=30,25], EntitySkeleton['Skeleton'/16357, l='MpServer', x=205,50, y=49,00, z=24,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntitySpider['Spider'/17135, l='MpServer', x=224,50, y=46,00, z=-53,50], EntitySheep['Sheep'/16623, l='MpServer', x=331,66, y=72,00, z=-33,78], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityZombie['Zombie'/15864, l='MpServer', x=261,50, y=47,00, z=66,50], EntityWitch['Witch'/16123, l='MpServer', x=214,31, y=14,00, z=-11,69], EntityXPOrb['Experience Orb'/17404, l='MpServer', x=258,28, y=76,00, z=-99,66], EntityWitch['Witch'/16124, l='MpServer', x=207,47, y=17,00, z=-12,13], EntityXPOrb['Experience Orb'/17405, l='MpServer', x=256,59, y=76,00, z=-99,72], EntityWitch['Witch'/16125, l='MpServer', x=218,50, y=14,00, z=-11,50], EntityEnderman['Enderman'/16894, l='MpServer', x=199,50, y=34,00, z=-26,50], EntityZombie['Zombie'/16639, l='MpServer', x=263,50, y=43,00, z=-35,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2125)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [EntityPlayerSP['xX_KrIsCrEeP_Xx'/6468, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options:
    Level spawn location: 220,00,64,00,256,00 - World: (220,64,256), Chunk: (at 12,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1410969 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 111 total; [EntityPlayerSP['xX_KrIsCrEeP_Xx'/6468, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityChicken['Dodo'/3074, l='MpServer', x=254,59, y=80,00, z=21,47], EntityXPOrb['Experience Orb'/17411, l='MpServer', x=244,59, y=77,00, z=-128,69], EntityChicken['Dodo'/3075, l='MpServer', x=253,81, y=80,00, z=24,50], EntityXPOrb['Experience Orb'/17412, l='MpServer', x=243,53, y=77,00, z=-127,63], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=221,16, y=79,00, z=52,63], EntityChicken['Dodo'/3090, l='MpServer', x=256,47, y=80,00, z=20,81], EntitySheep['Sheep'/16659, l='MpServer', x=349,38, y=71,09, z=7,50], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=148,81, y=64,00, z=26,69], EntityXPOrb['Experience Orb'/17431, l='MpServer', x=223,25, y=82,00, z=-93,91], EntityZombie['Zombie'/15899, l='MpServer', x=247,50, y=43,00, z=-47,50], EntityZombie['Zombie'/15900, l='MpServer', x=247,50, y=43,00, z=-48,50], EntityZombie['Zombie'/15901, l='MpServer', x=247,50, y=43,00, z=-49,50], EntityItem['item.item.egg'/12574, l='MpServer', x=256,03, y=80,00, z=21,13], EntityZombie['Zombie'/16678, l='MpServer', x=256,50, y=19,00, z=26,06], EntityZombie['Zombie'/17702, l='MpServer', x=256,50, y=29,02, z=-50,50], EntityZombie['Zombie'/16679, l='MpServer', x=257,50, y=18,00, z=15,50], EntityZombie['Zombie'/17703, l='MpServer', x=256,50, y=29,02, z=-49,50], EntitySkeleton['Skeleton'/16940, l='MpServer', x=211,50, y=56,00, z=23,50], EntityCreeper['Creeper'/15660, l='MpServer', x=221,50, y=61,00, z=34,50], EntityCreeper['Creeper'/15661, l='MpServer', x=222,50, y=61,00, z=33,50], EntityZombie['Zombie'/17715, l='MpServer', x=338,50, y=28,02, z=35,50], EntityZombie['Zombie'/17716, l='MpServer', x=340,50, y=28,02, z=38,50], EntityZombie['Zombie'/17717, l='MpServer', x=336,50, y=28,02, z=36,50], EntitySheep['Sheep'/3396, l='MpServer', x=263,47, y=85,00, z=-40,19], EntitySheep['Sheep'/3397, l='MpServer', x=198,72, y=90,00, z=-40,81], EntitySheep['Sheep'/16710, l='MpServer', x=353,38, y=75,00, z=9,19], EntitySheep['Sheep'/16713, l='MpServer', x=355,84, y=75,00, z=25,94], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityBat['Bat'/16474, l='MpServer', x=257,50, y=18,69, z=17,35], EntityBat['Bat'/16475, l='MpServer', x=242,49, y=21,33, z=32,67], EntityItem['item.item.arrow'/13664, l='MpServer', x=223,84, y=80,00, z=13,28], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28], EntityBat['Bat'/17768, l='MpServer', x=238,50, y=28,00, z=-55,50], EntityBat['Bat'/17770, l='MpServer', x=238,40, y=28,06, z=-56,33], EntitySkeleton['Skeleton'/14967, l='MpServer', x=233,50, y=42,00, z=-32,50], EntityBat['Bat'/17281, l='MpServer', x=223,66, y=39,06, z=23,68], EntityItem['item.item.egg'/11396, l='MpServer', x=253,75, y=80,00, z=24,41], EntityCreeper['Creeper'/17314, l='MpServer', x=320,25, y=30,30, z=-49,31], EntitySpider['Spider'/13475, l='MpServer', x=230,50, y=16,00, z=-24,50], EntityBat['Bat'/17572, l='MpServer', x=199,48, y=58,31, z=5,66], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityZombie['Zombie'/15529, l='MpServer', x=222,63, y=81,00, z=17,06], EntitySkeleton['Skeleton'/15530, l='MpServer', x=214,75, y=80,00, z=18,81], EntitySkeleton['Skeleton'/15531, l='MpServer', x=215,50, y=80,00, z=22,50], EntitySkeleton['Skeleton'/16300, l='MpServer', x=266,50, y=40,00, z=-10,50], EntitySkeleton['Skeleton'/16301, l='MpServer', x=268,50, y=40,00, z=-10,50], EntityCreeper['Creeper'/15534, l='MpServer', x=199,50, y=17,00, z=17,50], EntityEnderman['Enderman'/16562, l='MpServer', x=221,50, y=26,00, z=-65,50], EntityZombie['Zombie'/16819, l='MpServer', x=257,38, y=45,00, z=-42,00], EntityZombie['Zombie'/16820, l='MpServer', x=251,63, y=43,00, z=-54,13], EntityZombie['Zombie'/16821, l='MpServer', x=253,34, y=44,00, z=-52,19], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/2999, l='MpServer', x=214,03, y=82,50, z=63,50], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityArmorStand['Armor Stand'/3000, l='MpServer', x=213,50, y=80,00, z=57,50], EntitySkeleton['Skeleton'/16056, l='MpServer', x=200,88, y=41,00, z=51,44], EntityItemFrame['entity.ItemFrame.name'/3001, l='MpServer', x=214,03, y=80,50, z=61,50], EntityPlayerDummy['entity.rfpr.PlayerDummy.name'/186, l='MpServer', x=278,57, y=80,23, z=-8,73], EntityArmorStand['Armor Stand'/3002, l='MpServer', x=213,50, y=80,00, z=53,50], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/3003, l='MpServer', x=214,03, y=80,50, z=63,50], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityItemFrame['entity.ItemFrame.name'/3004, l='MpServer', x=214,03, y=80,50, z=62,50], EntityItemFrame['entity.ItemFrame.name'/3005, l='MpServer', x=214,03, y=80,50, z=60,50], EntitySkeleton['Skeleton'/17341, l='MpServer', x=220,50, y=80,00, z=14,50], EntityArmorStand['Armor Stand'/3006, l='MpServer', x=213,50, y=80,00, z=55,50], EntityBat['Bat'/15294, l='MpServer', x=196,53, y=55,45, z=5,46], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityOtherPlayerMP['animalking1001'/191, l='MpServer', x=154,34, y=63,67, z=22,28], EntityItemFrame['entity.ItemFrame.name'/3007, l='MpServer', x=214,03, y=80,50, z=59,50], EntityArmorStand['Armor Stand'/3008, l='MpServer', x=213,50, y=80,00, z=51,50], EntityBat['Bat'/17093, l='MpServer', x=213,54, y=48,82, z=7,71], EntityPainting['Painting'/63, l='MpServer', x=202,03, y=73,50, z=190,00], EntityPainting['Painting'/65, l='MpServer', x=205,97, y=73,50, z=190,00], EntityXPOrb['Experience Orb'/17355, l='MpServer', x=278,91, y=74,00, z=-106,78], EntityXPOrb['Experience Orb'/17356, l='MpServer', x=280,66, y=74,00, z=-107,25], EntityCreeper['Creeper'/14293, l='MpServer', x=246,50, y=15,00, z=-19,50], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityXPOrb['Experience Orb'/17375, l='MpServer', x=276,38, y=74,00, z=-102,41], EntityXPOrb['Experience Orb'/17376, l='MpServer', x=277,06, y=74,00, z=-102,59], EntityItem['item.item.string'/13537, l='MpServer', x=217,81, y=73,00, z=31,56], EntityXPOrb['Experience Orb'/13540, l='MpServer', x=216,59, y=73,00, z=32,28], EntityZombie['Zombie'/16356, l='MpServer', x=200,50, y=49,00, z=26,50], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityXPOrb['Experience Orb'/13541, l='MpServer', x=215,06, y=73,00, z=30,25], EntitySkeleton['Skeleton'/16357, l='MpServer', x=205,50, y=49,00, z=24,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntitySpider['Spider'/17135, l='MpServer', x=224,50, y=46,00, z=-53,50], EntitySheep['Sheep'/16623, l='MpServer', x=331,66, y=72,00, z=-33,78], EntityPainting['Painting'/66, l='MpServer', x=196,00, y=74,00, z=185,97], EntityPainting['Painting'/67, l='MpServer', x=203,03, y=73,50, z=194,50], EntityPainting['Painting'/69, l='MpServer', x=204,50, y=73,50, z=195,97], EntityZombie['Zombie'/15864, l='MpServer', x=261,50, y=47,00, z=66,50], EntityWitch['Witch'/16123, l='MpServer', x=214,31, y=14,00, z=-11,69], EntityXPOrb['Experience Orb'/17404, l='MpServer', x=258,28, y=76,00, z=-99,66], EntityWitch['Witch'/16124, l='MpServer', x=207,47, y=17,00, z=-12,13], EntityXPOrb['Experience Orb'/17405, l='MpServer', x=256,59, y=76,00, z=-99,72], EntityWitch['Witch'/16125, l='MpServer', x=218,50, y=14,00, z=-11,50], EntityEnderman['Enderman'/16894, l='MpServer', x=199,50, y=34,00, z=-26,50], EntityZombie['Zombie'/16639, l='MpServer', x=263,50, y=43,00, z=-35,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 255816736 bytes (243 MB) / 545984512 bytes (520 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_H6 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1563.jar)
    UCHIJA  Forge{11.14.4.1563} [Minecraft Forge](forge-1.8-11.14.4.1563.jar)
    UCHIJA  arkcraft{0.1.3-Alpha} [ARKCraft](arkcraft-0.1-alpha.jar)
    UCHIJA  hud{1.3.6} [Better HUD](Better HUD by NukeDuck [1.8][1.3.6].jar)
    UCHIJA  BetterFoliage{2.0.14} [Better Foliage](BetterFoliage-MC1.8-2.0.14.jar)
    UCHIJA  rfpr{7.0.0} [Real First-Person Render](Real First-Person Render-1.8-7.0.0.jar)
    Loaded coremods (and transformers):
BetterFoliageLoader (BetterFoliage-MC1.8-2.0.14.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
    Launched Version: 1.8-forge1.8-11.14.4.1563
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4404, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [[16x16]Plain Wood Doors V1.0 For MC 1.9.zip, ARKcraft.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
OptiFine Version: OptiFine_1.8_HD_U_H6
Render Distance Chunks: 13
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.4.0 - Build 20.19.15.4404
OpenGlRenderer: Intel(R) HD Graphics 5500
OpenGlVendor: Intel
CpuCount: 4
```

**Comment by LewisMcReu** [comment]
What were the circumstances of this crash? Did you click a block, use an item, ...?
This issue might also not be related to ARKCraft; it might be BetterFoliage acting up.
